controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_endeffector_controller
    type: $(arg fake_execution_type)
    joints:
      - joint7
      - joint8
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home
  - group: endeffector
    pose: open_gripper