controller_list:
  - name: fake_osam_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_8
      - joint_9
initial:  # Define initial robot poses per group
  - group: osam_arm
    pose: zero_arm
  - group: hand
    pose: open_hand