#Controller to control robot arm joints
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint0, joint1, joint2, joint3, joint4, joint5, joint6]

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint7, joint8]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

#Controller to control velocity of robot arm joints
joint_group_position_controller:
  type: "position_controllers/JointGroupPositionController"
  joints: [joint0, joint1, joint2, joint3, joint4, joint5, joint6]